version: '3'
services:
  fastapi-example:
    build: .
    image: ${DOCKER_USER}/fastapi-example:${DOCKER_TAG}
    ports:
    - "8080:8080"
    environment:
      LOG_LEVEL: "DEBUG"
      PORT: "8080"
